
name: Azure Deploy

on: 
 push: 
  branches:
   - main
  paths:
    - infrastructure/**
 pull_request:
  branches:
    - main
  paths:
    - infrastructure/**
 workflow_dispatch: # manual trigger

permissions:
  id-token: write
  contents: read

jobs:
 deploy-dev:
  runs-on: ubuntu-latest
  environment: Development
  steps:
    - uses: actions/checkout@v4

    - name: Azure login
      uses: azure/login@v2.1.1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

    - uses: Azure/CLI@v2
      with:
        inlineScript: |
          #!/bin/bash
          az group create --name ${{ vars.RESOURCE_GROUP_NAME }} --location ${{ vars.RESOURCE_GROUP_LOCATION }}
          echo "Azure resource group created"

    - name: Deploy  
      uses: azure/arm-deploy@v2
      with:
        scope: resourcegroup
        resourceGroupName: ${{ vars.RESOURCE_GROUP_NAME }}
        template: ./infrastructure/main.bicep
        parameters: pgSqlPassword=${{ secrets.PGSQL_PASSWORD }}

 deploy-stg:
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment: Staging
    steps:
      - uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2.1.1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - uses: Azure/CLI@v2
        with:
          inlineScript: |
            #!/bin/bash
            az group create --name ${{ vars.RESOURCE_GROUP_NAME }} --location ${{ vars.RESOURCE_GROUP_LOCATION }}
            echo "Azure resource group created"

      - name: Deploy  
        uses: azure/arm-deploy@v2
        with:
          scope: resourcegroup
          resourceGroupName: ${{ vars.RESOURCE_GROUP_NAME }}
          template: ./infrastructure/main.bicep
          parameters: pgSqlPassword=${{ secrets.PGSQL_PASSWORD }}

 deploy-prd:
    runs-on: ubuntu-latest
    needs: deploy-stg
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment: Production
    steps:
      - uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2.1.1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - uses: Azure/CLI@v2
        with:
          inlineScript: |
            #!/bin/bash
            az group create --name ${{ vars.RESOURCE_GROUP_NAME }} --location ${{ vars.RESOURCE_GROUP_LOCATION }}
            echo "Azure resource group created"

      - name: Deploy  
        uses: azure/arm-deploy@v2
        with:
          scope: resourcegroup
          resourceGroupName: ${{ vars.RESOURCE_GROUP_NAME }}
          template: ./infrastructure/main.bicep
          parameters: pgSqlPassword=${{ secrets.PGSQL_PASSWORD }}